### ISSUE TITLE
Add i18n labels to capabilities

### ISSUE THREAD

**Issue by mconlon17** [mconlon17/language-ontology#8]
## What term needs to be improved? (to add terms, please use Feature Request)

All CEFR capabilities

## What needs to be improved? (annotations, subsumption, class expressions, other)

Add french, german, italian, and spanish labels to the language capabilities

## Suggested improvement

Use Google translate (argh) to translate the english to these languages.  Add triples to iso-639-i18n-CEFR-definitions.nt

**Comment by hauschke** [comment]
At least when it comes to english-german, deepl.com is much better. The German one can be done/revised by the VIVO-DE community. We will find some volunteers.

**Comment by mconlon17** [comment]
Used deepl.com.  Added translations for labels and definitions for language and language capabilities for es, it, de, and fr.
